spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sse
    username: postgres
    password: 051099
    driver-class-name: org.postgresql.Driver
    #url: jdbc:sqlserver://aitutour.database.windows.net:1433;databaseName=ssegroup
    #username: sse
    #password: 1234567890Q!
    #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # max file size for uploading
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false # 开发时关闭缓存，方便调试
    enabled: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.jdbc.support.jdbcTransactionManager: debug



